package main

// Names by default for servers
var (
	Names = []string{
		"Captain Koons",
		"Bridget von Hammersmark",
		"Gogo Yubari",
		"Floyd",
		"The Gimp",
		"Max Cherry",
		"Hugo Stiglitz",
		"Vernita Green",
		"Pumpkin",
		"Honeybunny",
		"Louis Gara",
		"Mr Brown",
		"Lt Archie Hicox",
		"The Wolf",
		"Pai Mei",
		"Stephen",
		"Santanico Pandemonium",
		"Donny Donowitz",
		"O-Ren Ishii",
		"Marsellus Wallace",
		"Nice Guy Eddie",
		"Calvin Candie",
		"Butch Coolidge",
		"Mr Pink",
		"Richie Gecko",
		"Shosanna",
		"Mr White",
		"Mia Wallace",
		"Elle Driver",
		"Lt Aldo Raine",
		"Dr King Schultz",
		"Stuntman Mike",
		"Mr Orange",
		"Bill",
		"Vincent Vega",
		"Jackie Brown",
		"Django",
		"Col Hans Landa",
		"Mr Blonde",
		"Jules Winnfield",
		"Beatrix Kiddo",
	}
)
