package main

// Names by default for servers
var (
	Names = []string{
		"Captain Koons",
		"Butch Coolidge",
		"Hugo Stiglitz",
		"Vincent Vega",
		"Mia Wallace",
		"Marsellus Wallace",
		"Bridget von Hammersmark",
		"Gogo Yubari",
		"Floyd",
		"The Gimp",
		"Max Cherry",
		"Vernita Green",
		"Pumpkin",
		"Honeybunny",
		"Louis Gara",
		"Mr Brown",
		"Lt Archie Hicox",
		"The Wolf",
		"Pai Mei",
		"Stephen",
		"Santanico Pandemonium",
		"Donny Donowitz",
		"O-Ren Ishii",
		"Nice Guy Eddie",
		"Calvin Candie",
		"Mr Pink",
		"Richie Gecko",
		"Shosanna",
		"Mr White",
		"Elle Driver",
		"Lt Aldo Raine",
		"Dr King Schultz",
		"Stuntman Mike",
		"Mr Orange",
		"Bill",
		"Jackie Brown",
		"Django",
		"Col Hans Landa",
		"Mr Blonde",
		"Jules Winnfield",
		"Beatrix Kiddo",
	}
)
